# Generated by Django 4.2 on 2023-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('supply_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supply',
            },
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['barcode', 'supply_time'], name='supply_barcode_8de428_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['barcode', 'sale_time'], name='sale_barcode_c980e9_idx'),
        ),
    ]
