# Generated by Django 4.2 on 2023-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField(blank=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('saleTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('barcode', models.BigIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('supplyTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supply',
            },
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['barcode', 'supplyTime'], name='supply_barcode_a959c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['barcode', 'saleTime'], name='sale_barcode_e07969_idx'),
        ),
    ]
