# Generated by Django 4.2 on 2023-04-16 22:07

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='saleTime',
            field=api.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplyTime',
            field=api.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
    ]
